site_name: 'SAN-LO Networking'
site_description: 'A platform for all SAN LO networking'
plugins:
  - techdocs-core
nav:
  - Getting Started: index.md
  - Services:
    - Intro: services/intro.md
  - Networks:
    - Intro: networks/intro.md
  - Assets:
    - Diagrams: diagram.md
